### ISSUE TITLE
Two functions required, please take a look

### ISSUE THREAD

**Issue by chenxofhit** [boring-plans/boring-days#2]
1, If clicking on any cell, a dialog should appear;

2, The size of a cell can be adjusted.

**Comment by tkzt** [comment]
> 1, If clicking on any cell, a dialog should appear;

Now the time, to make everything simple and easy to use, a tooltip containing record details will pop up after cell clicking. I have no idea on what use the dialog mentioned here is for.

> 2, The size of a cell can be adjusted.

Do you mean that, to make this a configuration item, just like switching theme color or switching languages or ...

**Comment by chenxofhit** [comment]
> > 1, If clicking on any cell, a dialog should appear;
> 
> Now the time, to make everything simple and easy to use, a tooltip containing record details will pop up after cell clicking. I have no idea on what use the dialog mentioned here is for.
> 
> > 2, The size of a cell can be adjusted.
> 
> Do you mean that, to make this a configuration item, just like switching theme color or switching languages or ...

1， Quickly set a value  today for the very selected theme；

2， 10px is too small if the actual page is large enough but the number of the themes is small.

**Comment by tkzt** [comment]
Version 1.0.2 is now [alive](https://boring-plans.github.io/boring-days/#/)👻! What mainly has been updated:

- feat: add editing day support (triggering by clicking on cell when screen size is md and up, and clicking on edit-icon when sm and down)
- update: mouse-over to pop up day details when screen size is md and up, and triggering method remains when sm and down
- update: when md and up, cell size will be adjusted to 13px

Please check whether your requirements have been met😼.

What's more, the attribute `lastModifiedAt` of the object Record used to indicate record date, has already been renamed to `date` (which is much easier to understand). You may need to rename the column `lastModifiedAt` in LC console manually.

**Comment by chenxofhit** [comment]
@boring-plans it works now, thanks for your hard work.
